<?php

	//application details
		$apps[$x]['name'] = "Billing";
		$apps[$x]['uuid'] = "b12c9a8f-5e4d-4b3a-8f2e-1a2b3c4d5e6f";
		$apps[$x]['category'] = "Switch";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "1.0";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['url'] = "http://www.fusionpbx.com";
		$apps[$x]['description']['en-us'] = "Dynamic prepaid and digit-based billing for users and agents with rate plans supporting multiple prefixes.";
		$apps[$x]['description']['en-gb'] = "Dynamic prepaid and digit-based billing for users and agents with rate plans supporting multiple prefixes.";

	//permission details
		$y=0;
		$apps[$x]['permissions'][$y]['name'] = "billing_rate_view";
		$apps[$x]['permissions'][$y]['menu']['uuid'] = "b12c9a8f-5e4d-4b3a-8f2e-1a2b3c4d5e6f";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "billing_rate_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "billing_rate_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "billing_rate_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "billing_balance_view";
		$apps[$x]['permissions'][$y]['menu']['uuid'] = "c23d0b9f-6f5e-5c4b-9g3f-2b3c4d5e6f7g";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$apps[$x]['permissions'][$y]['groups'][] = "user";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "billing_balance_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "billing_balance_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "billing_usage_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$apps[$x]['permissions'][$y]['groups'][] = "user";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "billing_agent_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$apps[$x]['permissions'][$y]['groups'][] = "agent";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "billing_agent_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";

	//default settings
		$y=0;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "billing";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "billing_enabled";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Enable or disable the billing system.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "billing";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "billing_currency";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "USD";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Default currency for billing.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "c3d4e5f6-a7b8-6c7d-0e1f-2a3b4c5d6e7f";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "billing";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "billing_increment";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "60";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Default billing increment in seconds (60 = per minute, 1 = per second).";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "d4e5f6a7-b8c9-7d8e-1f2a-3b4c5d6e7f8a";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "billing";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "low_balance_threshold";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "5";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Low balance notification threshold.";

	//schema details - billing_rates table
		$y=0;
		$apps[$x]['db'][$y]['table']['name'] = "v_billing_rates";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billing_rate_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "rate_name";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['search'] = 'true';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Name of the rate plan";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "rate_description";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['search'] = 'true';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Description of the rate plan";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "destination_prefix";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['search'] = 'true';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Destination prefix (e.g., 1, 44, 91)";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "rate_per_minute";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "numeric(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "real";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "decimal(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Rate per minute";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billing_increment";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Billing increment in seconds";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "minimum_duration";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Minimum duration in seconds";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "connection_fee";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "numeric(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "real";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "decimal(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Connection fee per call";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "currency";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Currency code (USD, EUR, etc.)";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "enabled";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enable or disable this rate";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Date the rate was created";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "User who created the rate";

	//schema details - billing_balances table
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_billing_balances";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billing_balance_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "extension_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_extensions";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "extension_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Extension/User UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "balance";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "numeric(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "real";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "decimal(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Current balance";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "currency";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Currency code";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "low_balance_alert";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enable low balance alert";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "low_balance_threshold";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "numeric(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "real";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "decimal(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Low balance threshold";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_updated";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Last updated timestamp";

	//schema details - billing_user_rates (many-to-many: users can have multiple prefixes)
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_billing_user_rates";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billing_user_rate_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "extension_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_extensions";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "extension_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Extension/User UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billing_rate_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_billing_rates";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "billing_rate_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Billing rate UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "enabled";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enable or disable this user rate";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Date assigned";

	//schema details - billing_usage table
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_billing_usage";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billing_usage_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "extension_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_extensions";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "extension_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Extension/User UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "xml_cdr_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_xml_cdr";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "xml_cdr_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "CDR UUID reference";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billing_rate_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_billing_rates";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "billing_rate_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Rate used for billing";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "destination_number";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['search'] = 'true';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Destination number";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "matched_prefix";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Matched prefix";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "duration";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Call duration in seconds";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billable_duration";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Billable duration (after increment)";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "rate_applied";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "numeric(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "real";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "decimal(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Rate applied per minute";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "connection_fee";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "numeric(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "real";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "decimal(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Connection fee charged";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "cost";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "numeric(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "real";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "decimal(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Total cost for this call";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "currency";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Currency code";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "call_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Call date and time";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Date record was created";

	//schema details - billing_agent_rates (call center agent specific rates)
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_billing_agent_rates";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billing_agent_rate_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "call_center_agent_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_call_center_agents";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "call_center_agent_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Call center agent UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billing_rate_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_billing_rates";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "billing_rate_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Billing rate UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "enabled";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enable or disable this agent rate";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Date assigned";

	//schema details - billing_balance_history (track all balance changes)
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_billing_balance_history";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billing_balance_history_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billing_balance_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_billing_balances";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "billing_balance_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Balance record UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "extension_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Extension UUID";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "transaction_type";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Transaction type: credit, debit, call_cost, adjustment";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "amount";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "numeric(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "real";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "decimal(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Amount of transaction (positive for credit, negative for debit)";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "balance_before";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "numeric(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "real";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "decimal(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Balance before transaction";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "balance_after";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "numeric(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "real";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "decimal(10,4)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Balance after transaction";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "description";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Transaction description";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "billing_usage_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Related billing usage UUID (if call cost)";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "created_by";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "User UUID who created the transaction";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Date of transaction";

?>
